#!/bin/sh
# ============================================================================
# customize03-shairport.sh — bake the AirPlay player (shairport-sync) release
#                             configuration into the rootfs, instead of leaving
#                             it only in one board's /etc
# ============================================================================
# Why this hook exists:
#   AirPlay playback stuttered on the board and two settings in
#   /etc/shairport-sync.conf fixed it, but only on that one board: reflashing
#   the image loses them. This hook moves that configuration into the rootfs build.
#
# Two settings are pinned (both in the 4.x `general` section):
#
#   1. interpolation = "basic"
#      By default shairport-sync's +/-1 frame drift correction goes through soxr,
#      and soxr_oneshot() rebuilds its filter every time. On this 650 MHz
#      Cortex-A9 one resample takes about 22.35 ms, just under the 30 ms
#      selection threshold, so soxr gets chosen; one thread then spins at 105%
#      CPU and the DAC queue underruns (Min DAC Queue = 0).
#      With "basic" (linear interpolation that inserts/drops whole frames) CPU
#      drops from 105% to 16.5% and the DAC queue holds around 0.96 s, with no
#      missing or late frames. A +/-1 frame correction is inaudible with linear
#      interpolation, and the shairport-sync documentation also recommends
#      basic/vernier on slow CPUs.
#
#   2. general.audio_backend_buffer_desired_length_in_seconds = 1.0
#      The default 0.2 s is drained by WiFi jitter on this machine (roaming
#      between BSSIDs of the same SSID). At 1.0 s the queue stays around 0.96 s;
#      the only cost is a slightly slower volume response, acceptable here.
#
# Also cleaned up: diagnostic settings enabled while debugging must not reach a
# release image --
#   diagnostics.log_verbosity must be 0 (3 while debugging)
#   diagnostics.statistics    must be "no" (yes while debugging)
#   diagnostics.log_output_to back to the default (stderr while debugging)
#
# Usage (mmdebstrap customize-stage hook; runs on the host, chroot dir is $1):
#   sh hooks/customize03-shairport.sh <rootfs dir>
# Idempotent: repeated runs give the same result; the config is edited if it
# exists and is created if it does not.
# ============================================================================
set -e

TARGET="${1:?usage: customize03-shairport.sh <rootfs dir>}"
CONF="$TARGET/etc/shairport-sync.conf"

mkdir -p "$TARGET/etc"

# --- Config file missing -> create a minimal working one ---------------------
# (Debian's shairport-sync package ships a fully commented sample; this is a
#  fallback so the release configuration is never empty even if upstream changes its packaging.)
if [ ! -f "$CONF" ]; then
    cat > "$CONF" <<'EOF'
// /etc/shairport-sync.conf - ZYBO Audio release configuration (generated by
// hooks/customize03-shairport.sh in zybo-debian; do not edit by hand, change
// the hook and rebuild the image). See the shairport-sync sample or `man shairport-sync`.

general =
{
	// 650MHz Cortex-A9: a soxr resample costs ~22.35ms (the 30ms threshold is
	// just met, so soxr is picked) and one thread spins at 105% CPU. "basic"
	interpolation = "basic";
	// linear interpolation is nearly free and a +/-1 frame correction is inaudible; the 0.2s default buffer underruns under WiFi jitter.
	audio_backend_buffer_desired_length_in_seconds = 1.0;
};

diagnostics =
{
	// Release configuration: all diagnostics off (only enabled while debugging)
	log_verbosity = 0;
	statistics = "no";
};
EOF
    echo "[hook] shairport-sync config missing -> created $CONF"
else
# --- Already exists -> edit in place (replace keys in a section; append missing keys at the section end) ---
awk '
BEGIN {
    SUBSEP = "\034"
    depth = 0; sec = ""; pend = ""

    nsec = 2; slist[1] = "general"; slist[2] = "diagnostics"

    nw["general"] = 2
    wkey["general", 1] = "interpolation"
    wval["general", 1] = "\tinterpolation = \"basic\"; // on a 650MHz A9 a soxr resample costs 22.35ms (30ms threshold); basic linear interpolation costs almost no CPU"
    wkey["general", 2] = "audio_backend_buffer_desired_length_in_seconds"
    wval["general", 2] = "\taudio_backend_buffer_desired_length_in_seconds = 1.0; // tolerates WiFi jitter; the 0.2s default underruns, the queue holds around 0.96s"

    nw["diagnostics"] = 2
    wkey["diagnostics", 1] = "log_verbosity"
    wval["diagnostics", 1] = "\tlog_verbosity = 0; // release configuration: not the 3 used while debugging"
    wkey["diagnostics", 2] = "statistics"
    wval["diagnostics", 2] = "\tstatistics = \"no\"; // release configuration: not the yes used while debugging"
}

# Section header on its own line: name =
depth == 0 && $0 ~ /^[ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*=[ \t]*$/ {
    pend = $0; sub(/[ \t]*=[ \t]*$/, "", pend); sub(/^[ \t]*/, "", pend)
    print; next
}

# Section header and opening brace on one line: name = {
$0 ~ /^[ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*=[ \t]*\{[ \t]*$/ {
    s = $0; sub(/[ \t]*=.*/, "", s); sub(/^[ \t]*/, "", s)
    print; sec = s; depth = 1; seen[s] = 1; next
}

# Opening brace (following a section header on the previous line)
depth == 0 && $0 ~ /^[ \t]*\{[ \t]*$/ {
    print; sec = pend; depth = 1; seen[sec] = 1; next
}

# End of section: append any missing mandatory keys for that section
depth == 1 && $0 ~ /^[ \t]*\}[ \t]*;?[ \t]*$/ {
    for (i = 1; i <= nw[sec]; i++) {
        k = sec SUBSEP wkey[sec, i]
        if (!(k in found)) { print wval[sec, i]; found[k] = 1 }
    }
    print; sec = ""; depth = 0; next
}

{
    if (depth == 1 && sec != "") {
        t = $0
        sub(/^[ \t]+/, "", t)
        active = 1
        if (t ~ /^\/\//) { active = 0; sub(/^\/\/[ \t]*/, "", t) }
        key = t
        sub(/[ \t]*=.*/, "", key)
        if (key ~ /^[A-Za-z_][A-Za-z0-9_]*$/) {
            for (i = 1; i <= nw[sec]; i++) {
                if (key == wkey[sec, i]) {
                    k = sec SUBSEP key
                    if (!(k in found)) { print wval[sec, i]; found[k] = 1 }
                    next
                }
            }
            # log_output_to = "stderr" used while debugging must not stay in a release config (the default is syslog)
            if (sec == "diagnostics" && key == "log_output_to" && active) {
                print "//\tlog_output_to = \"syslog\"; // release configuration: use the default; only set \"stderr\" while debugging"
                next
            }
        }
    }
    print
}

# The file has no general / diagnostics section at all -> append them at the end
END {
    for (j = 1; j <= nsec; j++) {
        s = slist[j]
        if (!(s in seen)) {
            print ""
            print s " ="
            print "{"
            for (i = 1; i <= nw[s]; i++) print wval[s, i]
            print "};"
        }
    }
}
' "$CONF" > "$CONF.zybo-new"
    mv -f "$CONF.zybo-new" "$CONF"
fi

# --- Verify: all four keys are in place and no diagnostic key holds a debugging value ---
fail() { echo "[hook] ERROR: shairport-sync config validation failed: $1" >&2; exit 1; }

grep -qE '^[[:space:]]*interpolation[[:space:]]*=[[:space:]]*"basic"[[:space:]]*;' "$CONF" \
    || fail 'interpolation is not "basic"'
grep -qE '^[[:space:]]*audio_backend_buffer_desired_length_in_seconds[[:space:]]*=[[:space:]]*1\.0[[:space:]]*;' "$CONF" \
    || fail 'audio_backend_buffer_desired_length_in_seconds is not 1.0'
grep -qE '^[[:space:]]*log_verbosity[[:space:]]*=[[:space:]]*0[[:space:]]*;' "$CONF" \
    || fail 'diagnostics.log_verbosity is not 0'
grep -qE '^[[:space:]]*statistics[[:space:]]*=[[:space:]]*"no"[[:space:]]*;' "$CONF" \
    || fail 'diagnostics.statistics is not "no"'
grep -qE '^[[:space:]]*log_verbosity[[:space:]]*=[[:space:]]*3' "$CONF" \
    && fail 'debugging value log_verbosity = 3 is still present'

# The same key must not appear twice in a section (libconfig fails to parse and shairport-sync will not start)
for k in interpolation audio_backend_buffer_desired_length_in_seconds log_verbosity statistics; do
    n="$(grep -cE "^[[:space:]]*${k}[[:space:]]*=" "$CONF" || true)"
    [ "$n" -eq 1 ] || fail "key $k appears $n times (must be exactly 1; duplicate keys make shairport-sync refuse to start)"
done

echo "[hook] shairport-sync configuration applied"
grep -nE '^[[:space:]]*(interpolation|audio_backend_buffer_desired_length_in_seconds|log_verbosity|statistics)[[:space:]]*=' "$CONF" | sed 's/^/  /'
